// __dev__/ts_solid/src/app.tsx
import { Component, createSignal } from 'solid-js'

export const App: Component = () => {
	const [count, setCount] = createSignal(0)
	function increment() {
		setCount(prev => prev + 1)
	}

	return (
		<div class={'text-8 flex flex-col w-full h-screen items-center justify-center'}>
			<div class={'font-bold'}>{count()}</div>
			<button class={'cursor-pointer text-4'} onClick={increment}>
				increment {Math.random()}
			</button>
		</div>
	)
}

// __dev__/penpot/template/react-ts/plugin-name/src/app.tsx
import {useEffect, useState} from "react"

export function App() {
  const [count, setCount] = useState(0)
  const [msgCount, setMsgCount] = useState(count)

  useEffect(() => {
    window.addEventListener('message', (event: MessageEvent<UiMessage<MessageType>>) => {
      onMessage(event, 'COUNT', _event => {
        setMsgCount(_event.data.data)
      })
    })
  }, [])

  function updateCount () {
    const newCount = count + 1
    setCount(newCount)
    snedMessageToPenpot({type: 'COUNT', data: newCount})
  }

  return <div className="min-h-screen min-w-full bg-white flex items-center content-center justify-center flex-wrap">
    <div className="w-full text-[36rem] font-bold text-center">Welcome plugin with React-TS and Tailwindcss!</div>
    <div className={'text-black text-center text-[32rem]'}>
      <div className={'cursor-pointer'} onClick={updateCount}>From UI: {count}</div>
      <div className={'cursor-pointer'} onClick={updateCount}>From Penpot: {msgCount}</div>
    </div>
  </div>
}

function snedMessageToPenpot <T extends MessageType>(msg: PenpotMessage<T>) {
  parent.postMessage(msg, '*')
}

function onMessage <T extends MessageType>(event: MessageEvent<UiMessage<T>>, type: T, callback: (event: MessageEvent<UiMessage<T>>) => void) {
  if (event.data.type === type) {
    callback(event)
  }
}
